### ISSUE TITLE
License

### ISSUE THREAD

**Issue by piyueh** [quantom-collab/tiktaalik#1]
@adamfreese  GPL (the current license) is like a virus. It forces all derived works (including but not limited to all code that uses this package) to also use the GPL license and restrains developers from choosing other licenses. If this is the intention, then feel free to close this issue. If not, I would suggest using other open-source license, e.g., MIT, BSD-3, etc.

**Comment by adamfreese** [comment]
This was the intention, but I am willing to reconsider. If not GPL, I'd use the BSD-3, which is standard for software developed at JLab.

**Comment by adamfreese** [comment]
I have followed your suggestion and changed the license.
